# Generated by Django 5.1.5 on 2025-02-03 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnstile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnstileLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code_scan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied')], max_length=50)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turnstile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnstile_logs', to='visitor.turnstile')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('token', models.CharField(max_length=255)),
                ('qr', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='turnstile',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnstile_entries', to='visitor.visitor'),
        ),
    ]
