# Generated by Django 5.1.5 on 2025-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='token',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='email',
            new_name='visitor_email',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='mobile',
            new_name='visitor_mobile',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='visitor_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='qr',
        ),
        migrations.AddField(
            model_name='visitor',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
